export enum MySQLEnvironments{
    HOST = "mysql.MYSQL_HOST",
    PORT = "mysql.MYSQL_PORT",
    USERNAME = "mysql.MYSQL_USERNAME",
    PASSWORD = "mysql.MYSQL_PASSWORD",
    DATABASE_NAME = "mysql.MYSQL_DATABASE_NAME", 
    ENTITIES = "mysql.MYSQL_ENTITIES",
    AUTO_LOAD_ENTITIES = "mysql.MYSQL_AUTO_LOAD_ENTITIES",
    MIGRATIONS = "mysql.MYSQL_MIGRATIONS",
    MIGRATIONS_TABLE_NAME = "mysql.MYSQL_MIGRATIONS_TABLE_NAME",
    MIGRATIONS_RUN = "mysql.MYSQL_MIGRATIONS_RUN",
    LOGGING = "mysql.MYSQL_LOGGING",
    SYNCHRONIZE = "mysql.MYSQL_SYNCHRONIZE",
    MIGRATIONS_DIR = "mysql.MYSQL_MIGRATIONS_DIR"
}