export enum MySQLEnvironmentsEnum{
    MYSQL_HOST = "mysql.MYSQL_HOST",
    MYSQL_PORT = "mysql.MYSQL_PORT",
    MYSQL_USERNAME = "mysql.MYSQL_USERNAME",
    MYSQL_PASSWORD = "mysql.MYSQL_PASSWORD",
    MYSQL_DATABASE_NAME = "mysql.MYSQL_DATABASE_NAME", 
    MYSQL_ENTITIES = "mysql.MYSQL_ENTITIES",
    MYSQL_AUTO_LOAD_ENTITIES = "mysql.MYSQL_AUTO_LOAD_ENTITIES",
    MYSQL_MIGRATIONS = "mysql.MYSQL_MIGRATIONS",
    MYSQL_MIGRATIONS_TABLE_NAME = "mysql.MYSQL_MIGRATIONS_TABLE_NAME",
    MYSQL_MIGRATIONS_RUN = "mysql.MYSQL_MIGRATIONS_RUN",
    MYSQL_LOGGING = "mysql.MYSQL_LOGGING",
    MYSQL_SYNCHRONIZE = "mysql.MYSQL_SYNCHRONIZE",
    MYSQL_MIGRATIONS_DIR = "mysql.MYSQL_MIGRATIONS_DIR"
}